# specify include all rules common to others
include: "rules/common.smk"

## Target:
# rule all:
#     input:
#         "results/multiqc/trimmed/multiqc_report.html"

## Rules to include:

include: "rules/qc_raw.smk"
include: "rules/trimgalore.smk"
include: "rules/qc_trimmed.smk"
# include: "rules/[STAR rule]"
