# specify include all rules common to others
include: "rules/common.smk"

## Target:
rule all:
    input:
        #the last output

## Rules to include:

include: "rules/qc_raw"
include: "rules/trimgalore"
include: "rules/qc_trimmed"
include: "rules/[STAR rule]"
