samples:
    4438_R1: data/samples/4438_S1_L002_R1_001.fastq.gz
    4438_R2: data/samples/4438_S1_L002_R2_001.fastq.gz
    4460_R1: data/samples/4460_S2_L002_R1_001.fastq.gz
    4460_R2: data/samples/4460_S2_L002_R2_001.fastq.gz
    4474_R1: data/samples/4474_S3_L002_R1_001.fastq.gz
    4474_R2: data/samples/4474_S3_L002_R2_001.fastq.gz
    4501_R1: data/samples/4501_S4_L002_R1_001.fastq.gz
    4501_R2: data/samples/4501_S4_L002_R2_001.fastq.gz
    4510_R1: data/samples/4510_S5_L002_R1_001.fastq.gz
    4510_R2: data/samples/4510_S5_L002_R2_001.fastq.gz
    4520_R1: data/samples/4520_S6_L002_R1_001.fastq.gz
    4520_R2: data/samples/4520_S6_L002_R2_001.fastq.gz
    DC1MINUS_R1: data/samples/DC1MINUS_S7_L002_R1_001.fastq.gz
    DC1MINUS_R2: data/samples/DC1MINUS_S7_L002_R2_001.fastq.gz
    DC1PLUS_R1: data/samples/DC1PLUS_S8_L002_R1_001.fastq.gz
    DC1PLUS_R2: data/samples/DC1PLUS_S8_L002_R2_001.fastq.gz
    DC2MINUS_R1: data/samples/DC2MINUES_S9_L002_R1_001.fastq.gz
    DC2MINUS_R2: data/samples/DC2MINUES_S9_L002_R2_001.fastq.gz
    DC2PLUS_R1: data/samples/DC2PLUS_S10_L002_R1_001.fastq.gz
    DC2PLUS_R2: data/samples/DC2PLUS_S10_L002_R2_001.fastq.gz
    DC2POOL_I1: data/samples/DC2Pool_NoIndex_L001_I1_001.fastq.gz
    DC2POOL_R2: data/samples/DC2Pool_NoIndex_L001_R2_001.fastq.gz
    DC3POOL_I1: data/samples/DC3Pool_NoIndex_L001_I1_001.fastq.gz
    DC3POOL_R1: data/samples/DC3Pool_NoIndex_L001_R1_001.fastq.gz
    DC3POOL_R2: data/samples/DC3Pool_NoIndex_L001_R2_001.fastq.gz
    DC4MINUS_R1: data/samples/DC4MINUS_S11_L002_R1_001.fastq.gz
    DC4MINUS_R2: data/samples/DC4MINUS_S11_L002_R2_001.fastq.gz
    DC4PLUS_R1: data/samples/DC4PLUS_S12_L002_R1_001.fastq.gz
    DC4PLUS_R2: data/samples/DC4PLUS_S12_L002_R2_001.fastq.gz
    DCPOOL_R1: data/samples/DC2Pool_NoIndex_L001_R1_001.fastq.gz
    Mischiefminus_R1: data/samples/Mischief_Minus_S12_L002_R1_001.fastq.gz
    Mischiefminus_R2: data/samples/Mischief_Minus_S12_L002_R2_001.fastq.gz
    Mischiefplus_R1: data/samples/Mischief_Plus_S11_L002_R1_001.fastq.gz
    Mischiefplus_R2: data/samples/Mischief_Plus_S11_L002_R2_001.fastq.gz
    X2654MINUS_R1: data/samples/X2654MINUS_S13_L002_R1_001.fastq.gz
    X2654MINUS_R2: data/samples/X2654MINUS_S13_L002_R2_001.fastq.gz
    X2654PLUS_R1: data/samples/X2654PLUS_S14_L002_R1_001.fastq.gz
    X2654PLUS_R2: data/samples/X2654PLUS_S14_L002_R2_001.fastq.gz
