species: Felis gattus, Puma concolor

run_dir: data/

# within the run_dir is the samples file
samples: felv_metadata.tsv

results:
    fastqc_raw: "results/fastqc/raw/"
    multiqc_raw: "results/multiqc/raw/"
    trimgalore: "data/trimmed/"
    fastqc_trimmed: "results/fastqc/trimmed/"
    multiqc_trimmed: "results/multiqc/trimmed/"

genomes:
  PumCon1.0:
    url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/327/715/GCF_003327715.1_PumCon1.0/GCF_003327715.1_PumCon1.0_genomic.fna.gz
  Felis_catus_9.0:
    url: https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Felis_catus/latest_assembly_versions/GCF_000181335.3_Felis_catus_9.0/GCF_000181335.3_Felis_catus_9.0_genomic.fna

proteomes:
  PumCon1.0:
    url: https://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003/327/715/GCF_003327715.1_PumCon1.0/GCF_003327715.1_PumCon1.0_protein.faa.gz
  Felis_catus_9.0:
    url: https://ftp.ncbi.nlm.nih.gov/genomes/refseq/vertebrate_mammalian/Felis_catus/latest_assembly_versions/GCF_000181335.3_Felis_catus_9.0/GCF_000181335.3_Felis_catus_9.0_protein.faa.gz
