species: Felis gattus, Puma concolor

run_dir: data

# within the run_dir is the samples file
samples: felv_metadata.txt

results:
    fastqc_raw: "results/fastqc/raw/"
    multiqc_raw: "results/multiqc/raw/"
    trimgalore: "data/trimmed/"
    fastqc_trimmed: "results/fastqc/trimmed/"
    multiqc_trimmed: "results/multiqc/trimmed/"
